// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for CreateStealthSafeFunction
 */
export interface CreateStealthSafeFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/lambda-functions/create-stealth-safe/create-stealth-safe.
 */
export class CreateStealthSafeFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: CreateStealthSafeFunctionProps) {
    super(scope, id, {
      description: 'src/lambda-functions/create-stealth-safe/create-stealth-safe.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/lambda-functions/create-stealth-safe/create-stealth-safe.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}