// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for FetchPricesFunction
 */
export interface FetchPricesFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/lambda-functions/fetch-prices/fetch-prices.
 */
export class FetchPricesFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: FetchPricesFunctionProps) {
    super(scope, id, {
      description: 'src/lambda-functions/fetch-prices/fetch-prices.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/lambda-functions/fetch-prices/fetch-prices.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}