// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for AlchemyWebhookListenerFunction
 */
export interface AlchemyWebhookListenerFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/lambda-functions/alchemy-webhook-listener/alchemy-webhook-listener.
 */
export class AlchemyWebhookListenerFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: AlchemyWebhookListenerFunctionProps) {
    super(scope, id, {
      description: 'src/lambda-functions/alchemy-webhook-listener/alchemy-webhook-listener.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/lambda-functions/alchemy-webhook-listener/alchemy-webhook-listener.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}