// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for ExecuteAutoEarnFunction
 */
export interface ExecuteAutoEarnFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/lambda-functions/execute-auto-earn/execute-auto-earn.
 */
export class ExecuteAutoEarnFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: ExecuteAutoEarnFunctionProps) {
    super(scope, id, {
      description: 'src/lambda-functions/execute-auto-earn/execute-auto-earn.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/lambda-functions/execute-auto-earn/execute-auto-earn.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}